package test;

import static org.junit.Assert.*;
import java.io.*;
import org.junit.Test;

/** Class automatically generated by YETI **/
public class YetiChess1 {

   /** Test case automatically generated by YETI **/
   @Test public void test_1() throws Exception {
      run.Main v1=new run.Main();
      /**BUG FOUND: RUNTIME EXCEPTION**/ // time:1355223203386
      /**YETI EXCEPTION - START 
      java.lang.NullPointerException
      	at run.Main.printBoard(Main.java:145)
      	at run.Main.<init>(Main.java:20)
      YETI EXCEPTION - END**/ 
      /** original locs: 2 minimal locs: 1**/
   
   }


   /** Test case automatically generated by YETI **/
   @Test public void test_2() throws Exception {
      int v2439=run.Main.getAlphaConversion((java.lang.String)null);
      /**BUG FOUND: RUNTIME EXCEPTION**/ // time:1355223207741
      /**YETI EXCEPTION - START 
      java.lang.NullPointerException
      	at run.Main.getAlphaConversion(Main.java:74)
      YETI EXCEPTION - END**/ 
      /** original locs: 4908 minimal locs: 1**/
   
   }


   /** Test case automatically generated by YETI **/
   @Test public void test_3() throws Exception {
      yetihelper.Helper v76=new yetihelper.Helper(); // time:1355223203509
      int v77=-2147483647; // time:1355223203509
      java.lang.Integer v78=v76.dummyInteger((int)v77); // time:1355223203509
      material.Square v79=new material.Square((java.lang.Integer)v78,(java.lang.Integer)v78); // time:1355223203509
      java.lang.Integer v80=v79.getRow(); // time:1355223203509
      material.Square v286=new material.Square((java.lang.Integer)v80,(java.lang.Integer)null); // time:1355223203642
      material.Board v313=new material.Board(); // time:1355223203665
      material.Piece v321=v313.getSquare((material.Square)v286);
      /**BUG FOUND: RUNTIME EXCEPTION**/ // time:1355223203669
      /**YETI EXCEPTION - START 
      java.lang.NullPointerException
      	at material.Square.hashCode(Square.java:49)
      	at java.util.HashMap.get(Unknown Source)
      	at material.Board.getSquare(Board.java:64)
      YETI EXCEPTION - END**/ 
      /** original locs: 1384 minimal locs: 8**/
   
   }


   /** Test case automatically generated by YETI **/
   @Test public void test_4() throws Exception {
      yetihelper.Helper v76=new yetihelper.Helper(); // time:1355223203509
      int v77=-2147483647; // time:1355223203509
      java.lang.Integer v78=v76.dummyInteger((int)v77); // time:1355223203509
      material.Square v79=new material.Square((java.lang.Integer)v78,(java.lang.Integer)v78); // time:1355223203509
      java.lang.Integer v80=v79.getRow(); // time:1355223203509
      material.Square v286=new material.Square((java.lang.Integer)v80,(java.lang.Integer)null); // time:1355223203642
      int v2252=v286.hashCode();
      /**BUG FOUND: RUNTIME EXCEPTION**/ // time:1355223207190
      /**YETI EXCEPTION - START 
      java.lang.NullPointerException
      	at material.Square.hashCode(Square.java:49)
      YETI EXCEPTION - END**/ 
      /** original locs: 4674 minimal locs: 7**/
   
   }


/** Non-Unique bugs: 565, Unique Bugs: 4, Logs size (locs): 9519**/

}