package test;

import static org.junit.Assert.*;
import java.io.*;
import org.junit.Test;

/** Class automatically generated by YETI **/
public class YetiChessUltimate {

   /** Test case automatically generated by YETI **/
   @Test public void test_1() throws Exception {
      int v7=-3; // time:1355225044102
      java.lang.Integer v8=yetihelper.Helper.dummyInteger((int)v7); // time:1355225044102
      material.Square v9=new material.Square((java.lang.Integer)v8,(java.lang.Integer)v8); // time:1355225044102
      java.util.List v38=yetihelper.Helper.smartList(); // time:1355225044160
      material.Square v42=new material.Square((java.util.List)v38); // time:1355225044167
      java.lang.Integer v83=v9.getRow(); // time:1355225044203
      java.lang.Integer v119=v42.getCol(); // time:1355225044213
      material.Board v212=new material.Board(); // time:1355225044282
      material.Square v453=new material.Square((java.lang.Integer)v119,(java.lang.Integer)v83); // time:1355225044382
      v212.movePiece((material.Piece)null,(material.Square)v453);
      /**BUG FOUND: RUNTIME EXCEPTION**/ // time:1355225044399
      /**YETI EXCEPTION - START 
      java.lang.NullPointerException
      	at material.Board.movePiece(Board.java:126)
      YETI EXCEPTION - END**/ 
      /** original locs: 720 minimal locs: 10**/
   
   }


   /** Test case automatically generated by YETI **/
   @Test public void test_2() throws Exception {
      test.YetiChessUltimate v0=new test.YetiChessUltimate(); // time:1355225044098
      java.lang.String v1=v0.toString(); // time:1355225044098
      int v7=-3; // time:1355225044102
      java.lang.Integer v8=yetihelper.Helper.dummyInteger((int)v7); // time:1355225044102
      material.Square v9=new material.Square((java.lang.Integer)v8,(java.lang.Integer)v8); // time:1355225044102
      material.Board v12=new material.Board(); // time:1355225044103
      java.lang.String v14=v12.toString(); // time:1355225044105
      material.Piece v15=new material.Piece((material.Square)v9,(java.lang.String)v14,(java.lang.String)v14); // time:1355225044105
      java.lang.Integer v26=v9.getRow(); // time:1355225044111
      material.Square v51=new material.Square((java.lang.Integer)v26,(java.lang.Integer)null); // time:1355225044172
      material.Piece v52=new material.Piece((material.Square)v51,(java.lang.String)null,(java.lang.String)v1); // time:1355225044172
      material.Board v92=new material.Board(); // time:1355225044205
      material.Square v132=v52.getPosition(); // time:1355225044220
      v92.movePieceBack((material.Piece)v15,(material.Square)v132);
      /**BUG FOUND: RUNTIME EXCEPTION**/ // time:1355225044220
      /**YETI EXCEPTION - START 
      java.lang.NullPointerException
      	at material.Square.hashCode(Square.java:49)
      	at java.util.HashMap.put(Unknown Source)
      	at material.Board.movePieceBack(Board.java:138)
      YETI EXCEPTION - END**/ 
      /** original locs: 188 minimal locs: 14**/
   
   }


   /** Test case automatically generated by YETI **/
   @Test public void test_3() throws Exception {
      int v7=-3; // time:1355225044102
      java.lang.Integer v8=yetihelper.Helper.dummyInteger((int)v7); // time:1355225044102
      material.Square v9=new material.Square((java.lang.Integer)v8,(java.lang.Integer)v8); // time:1355225044102
      material.Board v12=new material.Board(); // time:1355225044103
      java.lang.String v14=v12.toString(); // time:1355225044105
      material.Piece v15=new material.Piece((material.Square)v9,(java.lang.String)v14,(java.lang.String)v14); // time:1355225044105
      java.lang.Integer v26=v9.getRow(); // time:1355225044111
      material.Square v51=new material.Square((java.lang.Integer)v26,(java.lang.Integer)null); // time:1355225044172
      material.Board v92=new material.Board(); // time:1355225044205
      java.lang.String v103=v15.getColor(); // time:1355225044209
      material.Piece v122=new material.Piece((material.Square)v9,(java.lang.String)v103,(java.lang.String)v14); // time:1355225044214
      v92.setSquare((material.Square)v51,(material.Piece)v122);
      /**BUG FOUND: RUNTIME EXCEPTION**/ // time:1355225044267
      /**YETI EXCEPTION - START 
      java.lang.NullPointerException
      	at material.Square.hashCode(Square.java:49)
      	at java.util.HashMap.put(Unknown Source)
      	at material.Board.setSquare(Board.java:168)
      YETI EXCEPTION - END**/ 
      /** original locs: 273 minimal locs: 12**/
   
   }


   /** Test case automatically generated by YETI **/
   @Test public void test_4() throws Exception {
      material.Board v12=new material.Board(); // time:1355225044103
      test.YetiChess4 v65=new test.YetiChess4(); // time:1355225044173
      java.lang.String v66=v65.toString(); // time:1355225044173
      java.util.Set v73=v12.getPieces((java.lang.String)v66);
      /**BUG FOUND: RUNTIME EXCEPTION**/ // time:1355225044190
      /**YETI EXCEPTION - START 
      java.lang.NullPointerException
      	at material.Board.getPieces(Board.java:46)
      YETI EXCEPTION - END**/ 
      /** original locs: 96 minimal locs: 4**/
   
   }


   /** Test case automatically generated by YETI **/
   @Test public void test_5() throws Exception {
      test.YetiChessUltimate v0=new test.YetiChessUltimate(); // time:1355225044098
      java.lang.String v1=v0.toString(); // time:1355225044098
      int v7=-3; // time:1355225044102
      java.lang.Integer v8=yetihelper.Helper.dummyInteger((int)v7); // time:1355225044102
      material.Square v9=new material.Square((java.lang.Integer)v8,(java.lang.Integer)v8); // time:1355225044102
      material.Board v12=new material.Board(); // time:1355225044103
      java.lang.Integer v21=v9.getRow(); // time:1355225044107
      java.lang.Integer v26=v9.getRow(); // time:1355225044111
      java.util.List v28=yetihelper.Helper.smartList(); // time:1355225044111
      material.Square v29=new material.Square((java.util.List)v28); // time:1355225044111
      material.Square v51=new material.Square((java.lang.Integer)v26,(java.lang.Integer)null); // time:1355225044172
      material.Piece v52=new material.Piece((material.Square)v51,(java.lang.String)null,(java.lang.String)v1); // time:1355225044172
      java.lang.Integer v74=v29.getRow(); // time:1355225044196
      material.Square v75=new material.Square((java.lang.Integer)v21,(java.lang.Integer)v74); // time:1355225044196
      v12.movePieceBack((material.Piece)v52,(material.Square)v75);
      /**BUG FOUND: RUNTIME EXCEPTION**/ // time:1355225044197
      /**YETI EXCEPTION - START 
      java.lang.NullPointerException
      	at material.Square.hashCode(Square.java:49)
      	at java.util.HashMap.put(Unknown Source)
      	at material.Board.movePieceBack(Board.java:139)
      YETI EXCEPTION - END**/ 
      /** original locs: 107 minimal locs: 15**/
   
   }


   /** Test case automatically generated by YETI **/
   @Test public void test_6() throws Exception {
      material.Square v410=new material.Square((java.util.List)null);
      /**BUG FOUND: RUNTIME EXCEPTION**/ // time:1355225044357
      /**YETI EXCEPTION - START 
      java.lang.NullPointerException
      	at material.Square.<init>(Square.java:16)
      YETI EXCEPTION - END**/ 
      /** original locs: 593 minimal locs: 1**/
   
   }


   /** Test case automatically generated by YETI **/
   @Test public void test_7() throws Exception {
      material.Board v12=new material.Board(); // time:1355225044103
      v12.setAttackedSquares();
      /**BUG FOUND: RUNTIME EXCEPTION**/ // time:1355225044175
      /**YETI EXCEPTION - START 
      java.lang.NullPointerException
      	at material.Piece.oppColor(Piece.java:182)
      	at material.Board.setAttackedSquares(Board.java:154)
      YETI EXCEPTION - END**/ 
      /** original locs: 89 minimal locs: 2**/
   
   }


   /** Test case automatically generated by YETI **/
   @Test public void test_8() throws Exception {
      test.YetiChessUltimate v0=new test.YetiChessUltimate(); // time:1355225044098
      java.lang.String v1=v0.toString(); // time:1355225044098
      int v7=-3; // time:1355225044102
      java.lang.Integer v8=yetihelper.Helper.dummyInteger((int)v7); // time:1355225044102
      material.Square v9=new material.Square((java.lang.Integer)v8,(java.lang.Integer)v8); // time:1355225044102
      material.Board v12=new material.Board(); // time:1355225044103
      java.lang.Integer v26=v9.getRow(); // time:1355225044111
      java.util.List v38=yetihelper.Helper.smartList(); // time:1355225044160
      material.Square v39=new material.Square((java.util.List)v38); // time:1355225044160
      material.Square v51=new material.Square((java.lang.Integer)v26,(java.lang.Integer)null); // time:1355225044172
      material.Piece v52=new material.Piece((material.Square)v51,(java.lang.String)null,(java.lang.String)v1); // time:1355225044172
      java.util.List v79=v52.checkBoard((material.Square)v39,(material.Board)v12);
      /**BUG FOUND: RUNTIME EXCEPTION**/ // time:1355225044200
      /**YETI EXCEPTION - START 
      java.lang.NullPointerException
      	at material.Piece.setValidMoves(Piece.java:218)
      	at material.Piece.checkBoard(Piece.java:31)
      YETI EXCEPTION - END**/ 
      /** original locs: 115 minimal locs: 12**/
   
   }


   /** Test case automatically generated by YETI **/
   @Test public void test_9() throws Exception {
      java.util.List v28=yetihelper.Helper.smartList(); // time:1355225044111
      material.Square v214=new material.Square((java.util.List)v28); // time:1355225044282
      material.Board v366=new material.Board(); // time:1355225044344
      v366.movePieceBack((material.Piece)null,(material.Square)v214);
      /**BUG FOUND: RUNTIME EXCEPTION**/ // time:1355225044494
      /**YETI EXCEPTION - START 
      java.lang.NullPointerException
      	at material.Board.movePieceBack(Board.java:139)
      YETI EXCEPTION - END**/ 
      /** original locs: 1038 minimal locs: 4**/
   
   }


   /** Test case automatically generated by YETI **/
   @Test public void test_10() throws Exception {
      material.Board v145=new material.Board(); // time:1355225044236
      material.Piece v415=v145.getKing((java.lang.String)null);
      /**BUG FOUND: RUNTIME EXCEPTION**/ // time:1355225044360
      /**YETI EXCEPTION - START 
      java.lang.NullPointerException
      	at material.Board.getKing(Board.java:55)
      YETI EXCEPTION - END**/ 
      /** original locs: 604 minimal locs: 2**/
   
   }


   /** Test case automatically generated by YETI **/
   @Test public void test_11() throws Exception {
      int v7=-3; // time:1355225044102
      java.lang.Integer v8=yetihelper.Helper.dummyInteger((int)v7); // time:1355225044102
      material.Square v9=new material.Square((java.lang.Integer)v8,(java.lang.Integer)v8); // time:1355225044102
      java.lang.Integer v26=v9.getRow(); // time:1355225044111
      material.Square v51=new material.Square((java.lang.Integer)v26,(java.lang.Integer)null); // time:1355225044172
      int v125=v51.hashCode();
      /**BUG FOUND: RUNTIME EXCEPTION**/ // time:1355225044217
      /**YETI EXCEPTION - START 
      java.lang.NullPointerException
      	at material.Square.hashCode(Square.java:49)
      YETI EXCEPTION - END**/ 
      /** original locs: 169 minimal locs: 6**/
   
   }


   /** Test case automatically generated by YETI **/
   @Test public void test_12() throws Exception {
      material.Board v569=new material.Board(); // time:1355225044427
      v569.setAttackedSquares();
      /**BUG FOUND: RUNTIME EXCEPTION**/ // time:1355225044591
      /**YETI EXCEPTION - START 
      java.lang.NullPointerException
      	at material.Piece.getValidMoves(Piece.java:94)
      	at material.Board.setAttackedSquares(Board.java:154)
      YETI EXCEPTION - END**/ 
      /** original locs: 1289 minimal locs: 2**/
   
   }


   /** Test case automatically generated by YETI **/
   @Test public void test_13() throws Exception {
      test.YetiChessUltimate v0=new test.YetiChessUltimate(); // time:1355225044098
      java.lang.String v1=v0.toString(); // time:1355225044098
      int v7=-3; // time:1355225044102
      java.lang.Integer v8=yetihelper.Helper.dummyInteger((int)v7); // time:1355225044102
      material.Square v9=new material.Square((java.lang.Integer)v8,(java.lang.Integer)v8); // time:1355225044102
      java.lang.Integer v26=v9.getRow(); // time:1355225044111
      material.Square v51=new material.Square((java.lang.Integer)v26,(java.lang.Integer)null); // time:1355225044172
      material.Piece v52=new material.Piece((material.Square)v51,(java.lang.String)null,(java.lang.String)v1); // time:1355225044172
      material.Board v185=new material.Board(); // time:1355225044264
      boolean v202=true; // time:1355225044276
      java.util.Set v203=v52.getValidMoves((material.Board)v185,(boolean)v202);
      /**BUG FOUND: RUNTIME EXCEPTION**/ // time:1355225044276
      /**YETI EXCEPTION - START 
      java.lang.NullPointerException
      	at material.Piece.getValidMoves(Piece.java:94)
      YETI EXCEPTION - END**/ 
      /** original locs: 299 minimal locs: 11**/
   
   }


   /** Test case automatically generated by YETI **/
   @Test public void test_14() throws Exception {
      int v7=-3; // time:1355225044102
      java.lang.Integer v8=yetihelper.Helper.dummyInteger((int)v7); // time:1355225044102
      material.Square v9=new material.Square((java.lang.Integer)v8,(java.lang.Integer)v8); // time:1355225044102
      int v10=2147483646; // time:1355225044102
      java.lang.String v11=v9.getIntConversion((int)v10); // time:1355225044102
      java.lang.Integer v26=v9.getRow(); // time:1355225044111
      java.util.List v38=yetihelper.Helper.smartList(); // time:1355225044160
      material.Square v42=new material.Square((java.util.List)v38); // time:1355225044167
      char[] v46=v11.toCharArray(); // time:1355225044169
      java.lang.String v47=new java.lang.String((char[])v46); // time:1355225044169
      material.Piece v48=new material.Piece((material.Square)v42,(java.lang.String)v11,(java.lang.String)v47); // time:1355225044169
      material.Square v51=new material.Square((java.lang.Integer)v26,(java.lang.Integer)null); // time:1355225044172
      material.Board v92=new material.Board(); // time:1355225044205
      v92.movePiece((material.Piece)v48,(material.Square)v51);
      /**BUG FOUND: RUNTIME EXCEPTION**/ // time:1355225044238
      /**YETI EXCEPTION - START 
      java.lang.NullPointerException
      	at material.Square.hashCode(Square.java:49)
      	at java.util.HashMap.get(Unknown Source)
      	at material.Board.movePiece(Board.java:128)
      YETI EXCEPTION - END**/ 
      /** original locs: 216 minimal locs: 14**/
   
   }


   /** Test case automatically generated by YETI **/
   @Test public void test_15() throws Exception {
      test.YetiChessUltimate v0=new test.YetiChessUltimate(); // time:1355225044098
      java.lang.String v1=v0.toString(); // time:1355225044098
      int v7=-3; // time:1355225044102
      java.lang.Integer v8=yetihelper.Helper.dummyInteger((int)v7); // time:1355225044102
      material.Square v9=new material.Square((java.lang.Integer)v8,(java.lang.Integer)v8); // time:1355225044102
      int v10=2147483646; // time:1355225044102
      java.lang.String v11=v9.getIntConversion((int)v10); // time:1355225044102
      material.Board v12=new material.Board(); // time:1355225044103
      java.lang.String v14=v12.toString(); // time:1355225044105
      java.util.List v28=yetihelper.Helper.smartList(); // time:1355225044111
      material.Square v29=new material.Square((java.util.List)v28); // time:1355225044111
      java.util.List v38=yetihelper.Helper.smartList(); // time:1355225044160
      material.Square v39=new material.Square((java.util.List)v38); // time:1355225044160
      material.Square v42=new material.Square((java.util.List)v38); // time:1355225044167
      char[] v46=v11.toCharArray(); // time:1355225044169
      java.lang.String v47=new java.lang.String((char[])v46); // time:1355225044169
      material.Piece v48=new material.Piece((material.Square)v42,(java.lang.String)v11,(java.lang.String)v47); // time:1355225044169
      java.lang.String v70=v29.getIntConversion((int)v7); // time:1355225044174
      material.Square v91=new material.Square((java.util.List)v38); // time:1355225044203
      material.Piece v98=v12.getSquare((material.Square)v42); // time:1355225044208
      material.Piece v134=new material.Piece((material.Square)v91,(java.lang.String)v1,(java.lang.String)v14); // time:1355225044226
      material.Square v164=v98.getPosition(); // time:1355225044256
      material.Piece v171=new material.Piece((material.Square)v164,(java.lang.String)v70,(java.lang.String)v11); // time:1355225044258
      material.Board v325=new material.Board(); // time:1355225044326
      java.lang.String v372=v325.toString(); // time:1355225044345
      material.Square v487=v48.getPosition(); // time:1355225044396
      java.lang.Integer v525=v487.getRow(); // time:1355225044411
      int v928=-2147483648; // time:1355225044599
      java.lang.String v929=v39.getIntConversion((int)v928); // time:1355225044600
      material.Square v1017=v134.getPosition(); // time:1355225044648
      material.Piece v1018=new material.Piece((material.Square)v1017,(java.lang.String)v929,(java.lang.String)v372); // time:1355225044648
      java.lang.String v1168=v1018.toString(); // time:1355225044750
      java.lang.String v1236=v171.getType(); // time:1355225044796
      material.Square v1263=new material.Square((java.lang.Integer)v525,(java.lang.Integer)null); // time:1355225044813
      material.Piece v1655=new material.Piece((material.Square)v1263,(java.lang.String)v1168,(java.lang.String)v1236); // time:1355225045206
      material.Board v1667=new material.Board(); // time:1355225045217
      v1667.movePiece((material.Piece)v1655,(material.Square)null);
      /**BUG FOUND: RUNTIME EXCEPTION**/ // time:1355225045288
      /**YETI EXCEPTION - START 
      java.lang.NullPointerException
      	at material.Square.hashCode(Square.java:49)
      	at java.util.HashMap.put(Unknown Source)
      	at material.Board.movePiece(Board.java:126)
      YETI EXCEPTION - END**/ 
      /** original locs: 2368 minimal locs: 37**/
   
   }


   /** Test case automatically generated by YETI **/
   @Test public void test_16() throws Exception {
      int v7=-3; // time:1355225044102
      java.lang.Integer v8=yetihelper.Helper.dummyInteger((int)v7); // time:1355225044102
      material.Square v9=new material.Square((java.lang.Integer)v8,(java.lang.Integer)v8); // time:1355225044102
      java.lang.Integer v26=v9.getRow(); // time:1355225044111
      material.Square v51=new material.Square((java.lang.Integer)v26,(java.lang.Integer)null); // time:1355225044172
      material.Board v165=new material.Board(); // time:1355225044256
      material.Piece v357=v165.getSquare((material.Square)v51);
      /**BUG FOUND: RUNTIME EXCEPTION**/ // time:1355225044338
      /**YETI EXCEPTION - START 
      java.lang.NullPointerException
      	at material.Square.hashCode(Square.java:49)
      	at java.util.HashMap.get(Unknown Source)
      	at material.Board.getSquare(Board.java:64)
      YETI EXCEPTION - END**/ 
      /** original locs: 526 minimal locs: 7**/
   
   }


/** Non-Unique bugs: 139, Unique Bugs: 16, Logs size (locs): 6638**/

}