package test;

import static org.junit.Assert.*;
import java.io.*;
import org.junit.Test;

/** Class automatically generated by YETI **/
public class YetiChess4 {

   /** Test case automatically generated by YETI **/
   @Test public void test_0() throws Exception {
      new run.Main();
      /**BUG FOUND: RUNTIME EXCEPTION**/
      /** java.lang.NullPointerException
      	at run.Main.printBoard(Main.java:145)
      	at run.Main.<init>(Main.java:20)**/
   
   }


   /** Test case automatically generated by YETI **/
   @Test public void test_1() throws Exception {
      new material.Square((java.util.List)null);
      /**BUG FOUND: RUNTIME EXCEPTION**/
      /** java.lang.NullPointerException
      	at material.Square.<init>(Square.java:16)**/
   
   }


   /** Test case automatically generated by YETI **/
   @Test public void test_2() throws Exception {
      byte []v1987_bytes={};// class is not serializable, toString() returns: null
      material.Square v1987=(material.Square)(new ObjectInputStream(new ByteArrayInputStream(v1987_bytes)).readObject());
      byte []v1759_bytes={};// class is not serializable, toString() returns: 
//      	      A    B    C    D    E    F    G    H
//      
//      	8  | bR | bN | bB | bQ | bK | bB | bN | bR |  8
//      
//      	7  | bP | bP | bP | bP | bP | bP | bP | bP |  7
//      
//      	6  | -- | -- | -- | -- | -- | -- | -- | -- |  6
//      
//      	5  | -- | -- | -- | -- | -- | -- | -- | -- |  5
//      
//      	4  | -- | -- | -- | -- | -- | -- | -- | -- |  4
//      
//      	3  | -- | -- | -- | -- | -- | -- | -- | -- |  3
//      
//      	2  | wP | wP | wP | wP | wP | wP | wP | wP |  2
//      
//      	1  | wR | wN | wB | wQ | wK | wB | wN | wR |  1
//      
//      	      A    B    C    D    E    F    G    H
      
      material.Board v1759=(material.Board)(new ObjectInputStream(new ByteArrayInputStream(v1759_bytes)).readObject());
      v1759.getSquare((material.Square)v1987);
      /**BUG FOUND: RUNTIME EXCEPTION**/
      /** java.lang.NullPointerException
      	at material.Square.hashCode(Square.java:49)
      	at java.util.HashMap.get(Unknown Source)
      	at material.Board.getSquare(Board.java:64)**/
   
   }


   /** Test case automatically generated by YETI **/
   @Test public void test_3() throws Exception {
      byte []v5912_bytes={};// class is not serializable, toString() returns: null
      material.Square v5912=(material.Square)(new ObjectInputStream(new ByteArrayInputStream(v5912_bytes)).readObject());
      v5912.hashCode();
      /**BUG FOUND: RUNTIME EXCEPTION**/
      /** java.lang.NullPointerException
      	at material.Square.hashCode(Square.java:49)**/
   
   }


   /** Test case automatically generated by YETI **/
   @Test public void test_4() throws Exception {
      byte []v12717_bytes={(byte)-84,(byte)-19,(byte)0,(byte)5,(byte)115,(byte)114,(byte)0,(byte)19,(byte)106,(byte)97,(byte)118,(byte)97,(byte)46,(byte)117,(byte)116,(byte)105,(byte)108,(byte)46,(byte)65,(byte)114,(byte)114,(byte)97,(byte)121,(byte)76,(byte)105,(byte)115,(byte)116,(byte)120,(byte)-127,(byte)-46,(byte)29,(byte)-103,(byte)-57,(byte)97,(byte)-99,(byte)3,(byte)0,(byte)1,(byte)73,(byte)0,(byte)4,(byte)115,(byte)105,(byte)122,(byte)101,(byte)120,(byte)112,(byte)0,(byte)0,(byte)0,(byte)0,(byte)119,(byte)4,(byte)0,(byte)0,(byte)0,(byte)10,(byte)120};
      java.util.List v12717=(java.util.List)(new ObjectInputStream(new ByteArrayInputStream(v12717_bytes)).readObject());
      new material.Square((java.util.List)v12717);
      /**BUG FOUND: RUNTIME EXCEPTION**/
      /** java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
      	at java.util.ArrayList.rangeCheck(Unknown Source)
      	at java.util.ArrayList.get(Unknown Source)
      	at material.Square.<init>(Square.java:16)**/
   
   }


   /** Test case automatically generated by YETI **/
   @Test public void test_5() throws Exception {
      run.Main.getAlphaConversion((java.lang.String)null);
      /**BUG FOUND: RUNTIME EXCEPTION**/
      /** java.lang.NullPointerException
      	at run.Main.getAlphaConversion(Main.java:74)**/
   
   }


}