/*
 * generated by Xtext
 */
package fr.istic.m2.idm.xtext;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TopanlRuntimeModule extends fr.istic.m2.idm.xtext.AbstractTopanlRuntimeModule {

}
