// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package addressbookonline.domain;

import addressbookonline.domain.Address;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Address_Roo_Configurable {
    
    declare @type: Address: @Configurable;
    
}
