/*
* generated by Xtext
*/
package fr.istic.m2.idm.xtext.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class TopanlOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
