package test;

import static org.junit.Assert.*;
import java.io.*;
import org.junit.Test;

/** Class automatically generated by YETI **/
public class YetiTest {

   /** Test case automatically generated by YETI **/
   @Test public void test_0() throws Exception {
      byte []v15_bytes={};// class is not serializable, toString() returns: example.A@1988886
      example.A v15=(example.A)(new ObjectInputStream(new ByteArrayInputStream(v15_bytes)).readObject());
      example.YetiExample.illustrateAssertion((example.A)v15);
      /**BUG FOUND: RUNTIME EXCEPTION**/
      /** java.lang.AssertionError
      	at example.YetiExample.illustrateAssertion(YetiExample.java:62)**/
   
   }


   /** Test case automatically generated by YETI **/
   @Test public void test_1() throws Exception {
      example.YetiExample.illustrateUnusableConstructor((example.B)null);
      /**BUG FOUND: RUNTIME EXCEPTION**/
      /** java.lang.NullPointerException
      	at example.YetiExample.illustrateUnusableConstructor(YetiExample.java:31)**/
   
   }


   /** Test case automatically generated by YETI **/
   @Test public void test_2() throws Exception {
      byte []v170_bytes={};// class is not serializable, toString() returns: example.A@4ca42b
      example.A v170=(example.A)(new ObjectInputStream(new ByteArrayInputStream(v170_bytes)).readObject());
      example.YetiExample.illustrateBadConstructor((example.A)v170);
      /**BUG FOUND: RUNTIME EXCEPTION**/
      /** java.lang.NullPointerException
      	at example.A.useC(A.java:24)
      	at example.YetiExample.illustrateBadConstructor(YetiExample.java:23)**/
   
   }


   /** Test case automatically generated by YETI **/
   @Test public void test_3() throws Exception {
      byte []v98_bytes={};// class is not serializable, toString() returns: example.YetiExample@11bfcbe
      example.YetiExample v98=(example.YetiExample)(new ObjectInputStream(new ByteArrayInputStream(v98_bytes)).readObject());
      v98.illustrateRelevantValues((java.lang.String)null,(int)-7);
      /**BUG FOUND: RUNTIME EXCEPTION**/
      /** java.lang.NullPointerException
      	at example.YetiExample.illustrateRelevantValues(YetiExample.java:66)**/
   
   }


   /** Test case automatically generated by YETI **/
   @Test public void test_4() throws Exception {
      example.YetiExample.illustrateBadConstructor((example.A)null);
      /**BUG FOUND: RUNTIME EXCEPTION**/
      /** java.lang.NullPointerException
      	at example.YetiExample.illustrateBadConstructor(YetiExample.java:23)**/
   
   }


   /** Test case automatically generated by YETI **/
   @Test public void test_5() throws Exception {
      example.YetiExample.illustrateExactValue((int)1337);
      /**BUG FOUND: RUNTIME EXCEPTION**/
      /** java.lang.ArithmeticException: / by zero
      	at example.YetiExample.illustrateExactValue(YetiExample.java:19)**/
   
   }


   /** Test case automatically generated by YETI **/
   @Test public void test_6() throws Exception {
      example.YetiExample.illustrateRandomPlus((int)4);
      /**BUG FOUND: RUNTIME EXCEPTION**/
      /** java.lang.ArrayIndexOutOfBoundsException: 4
      	at example.YetiExample.illustrateRandomPlus(YetiExample.java:56)**/
   
   }


   /** Test case automatically generated by YETI **/
   @Test public void test_7() throws Exception {
      byte []v192482_bytes={(byte)-84,(byte)-19,(byte)0,(byte)5,(byte)116,(byte)0,(byte)11,(byte)112,(byte)114,(byte)105,(byte)110,(byte)116,(byte)95,(byte)99,(byte)111,(byte)108,(byte)111,(byte)114};
      java.lang.String v192482=(java.lang.String)(new ObjectInputStream(new ByteArrayInputStream(v192482_bytes)).readObject());
      byte []v185017_bytes={};// class is not serializable, toString() returns: example.YetiExample@23a6d8
      example.YetiExample v185017=(example.YetiExample)(new ObjectInputStream(new ByteArrayInputStream(v185017_bytes)).readObject());
      v185017.illustrateRelevantValues((java.lang.String)v192482,(int)-9);
      /**BUG FOUND: RUNTIME EXCEPTION**/
      /** java.lang.ArrayIndexOutOfBoundsException: -9
      	at example.YetiExample.illustrateRelevantValues(YetiExample.java:68)**/
   
   }


}