/*
 * generated by Xtext
 */
package fr.istic.m2.idm.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class TopanlUiModule extends fr.istic.m2.idm.xtext.ui.AbstractTopanlUiModule {
	public TopanlUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
