/*
* generated by Xtext
*/
package fr.istic.m2.idm.xtext.ui.contentassist;

import fr.istic.m2.idm.xtext.ui.contentassist.AbstractTopanlProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class TopanlProposalProvider extends AbstractTopanlProposalProvider {

}
