// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package addressbookonline.domain;

import addressbookonline.domain.Address;
import addressbookonline.domain.AddressDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect AddressDataOnDemand_Roo_DataOnDemand {
    
    declare @type: AddressDataOnDemand: @Component;
    
    private Random AddressDataOnDemand.rnd = new SecureRandom();
    
    private List<Address> AddressDataOnDemand.data;
    
    public Address AddressDataOnDemand.getNewTransientAddress(int index) {
        Address obj = new Address();
        setAddress1(obj, index);
        setAddress2(obj, index);
        setAddressState(obj, index);
        setCity(obj, index);
        setCountry(obj, index);
        setEmail(obj, index);
        setFirstname(obj, index);
        setLastname(obj, index);
        setMiddlename(obj, index);
        setPhone(obj, index);
        setPostalCode(obj, index);
        return obj;
    }
    
    public void AddressDataOnDemand.setAddress1(Address obj, int index) {
        String address1 = "address1_" + index;
        obj.setAddress1(address1);
    }
    
    public void AddressDataOnDemand.setAddress2(Address obj, int index) {
        String address2 = "address2_" + index;
        obj.setAddress2(address2);
    }
    
    public void AddressDataOnDemand.setAddressState(Address obj, int index) {
        String addressState = "addressState_" + index;
        obj.setAddressState(addressState);
    }
    
    public void AddressDataOnDemand.setCity(Address obj, int index) {
        String city = "city_" + index;
        obj.setCity(city);
    }
    
    public void AddressDataOnDemand.setCountry(Address obj, int index) {
        String country = "country_" + index;
        obj.setCountry(country);
    }
    
    public void AddressDataOnDemand.setEmail(Address obj, int index) {
        String email = "foo" + index + "@bar.com";
        obj.setEmail(email);
    }
    
    public void AddressDataOnDemand.setFirstname(Address obj, int index) {
        String firstname = "firstname_" + index;
        obj.setFirstname(firstname);
    }
    
    public void AddressDataOnDemand.setLastname(Address obj, int index) {
        String lastname = "lastname_" + index;
        obj.setLastname(lastname);
    }
    
    public void AddressDataOnDemand.setMiddlename(Address obj, int index) {
        String middlename = "middlename_" + index;
        obj.setMiddlename(middlename);
    }
    
    public void AddressDataOnDemand.setPhone(Address obj, int index) {
        String phone = "phone_" + index;
        obj.setPhone(phone);
    }
    
    public void AddressDataOnDemand.setPostalCode(Address obj, int index) {
        String postalCode = "postalCode_" + index;
        obj.setPostalCode(postalCode);
    }
    
    public Address AddressDataOnDemand.getSpecificAddress(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Address obj = data.get(index);
        Long id = obj.getId();
        return Address.findAddress(id);
    }
    
    public Address AddressDataOnDemand.getRandomAddress() {
        init();
        Address obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Address.findAddress(id);
    }
    
    public boolean AddressDataOnDemand.modifyAddress(Address obj) {
        return false;
    }
    
    public void AddressDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Address.findAddressEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Address' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Address>();
        for (int i = 0; i < 10; i++) {
            Address obj = getNewTransientAddress(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
