/*
 * generated by Xtext
 */
package fr.istic.m2.idm.xtext.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import fr.istic.m2.idm.xtext.ui.internal.TopanlActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class TopanlExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return TopanlActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return TopanlActivator.getInstance().getInjector(TopanlActivator.FR_ISTIC_M2_IDM_XTEXT_TOPANL);
	}
	
}
