/*
* generated by Xtext
*/
package fr.istic.m2.idm.xtext.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class TopanlAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("fr/istic/m2/idm/xtext/parser/antlr/internal/InternalTopanl.tokens");
	}
}
