/*
* generated by Xtext
*/
package fr.istic.m2.idm.xtext.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import fr.istic.m2.idm.xtext.services.TopanlGrammarAccess;

public class TopanlParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private TopanlGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected fr.istic.m2.idm.xtext.parser.antlr.internal.InternalTopanlParser createParser(XtextTokenStream stream) {
		return new fr.istic.m2.idm.xtext.parser.antlr.internal.InternalTopanlParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Geometry";
	}
	
	public TopanlGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(TopanlGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
